# The ultimate executable.
# This is the source of truth for the Ansible configuration.
# It will configure the designated hosts

---
- name: Physical Hardware Baseline
  hosts: metal # Runs on 192.168.2.244 once for each alias
  become: true
  tasks:
    - name: Update system
      ansible.builtin.apt:
        update_cache: true


    - name: Install essential packages
      ansible.builtin.apt:
        name:
          - vim
          - ufw
          - htop
          - git
          - curl
          - docker
          - kubernetes
        state: present
